export const TYPES = {
    CLEAR_STORE: 'CLEAR_STORE',
    LOGIN: 'LOGIN',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_ERROR: 'LOGIN_ERROR',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    FAVORITE_ADD: 'FAVORITE_ADD',
    FAVORITE_DELETE: 'FAVORITE_DELETE',
    NOTE_UPDATE: 'NOTE_UPDATE'
};
